fossasia/susi_desktop

.gitignore, Main/index.html, Main/main.css, README.md, index.js, package.json
Changes
- Added Basic electron environment
- Added Basic app
- Changed README.md
=> Basic Electron environment

index.js, package.json, src/main.js, static/css/normalize.css, static/index.html, static/main.css
Added a little bit of styling. Still some of the UI and API bugs persist. `Request` module is also removed and instead `fetch` which is a new standard is used. 
There's a bug in the bubble with class `from-them` which I am unable to fix. But I will be working on it as soon as the main bug, i.e. reply cache gets out of the way.
=> Add style to the app

static/index.html, static/main.css
#8 
- Changed background
- Changed input box design
- Changed button design
- New bubble design for messages
=> UI improvement

src/main.js, static/index.html
=> Add enter key to send

src/main.js, static/index.html, static/main.css
=> Added autoscroll to bottom

src/main.js, static/index.html, static/main.css
Now long input is shown across multiple lines
=> fixes #18 - Implemented a multiline text box

src/main.js
Now blanl messages will no more be sent
=> fixes #23 - Stopped sending blank messages

index.js, src/main.js, static/index.html, static/main.css, static/themes/dark_theme.css, static/themes/light_theme.css
Added a switch theme option by which user can choose between light theme
and dark theme
=> fixes #27 - Added a switch theme option

src/main.js
Now the user gets the response immediately after he asks anything.
=> fixes #33 - fixes response lag

package.json
fixes #45 
basic changes in package.json
=> fixes #45, update package.json

CONTRIBUTING.md
=> fixes #49, Added CONTRIBUTING.md

.editorconfig, .gitattributes
=> fixes #51, added .gitattr and .editorconfig

app/main/index.js
=> fixes #58, fixes travis build

package.json
=> fixes #56, updated package.json

app/package.json
=> fixes #61, added electron-debug in app dependencies as well

README.md
=> fixes #60, updated readme as per the requirements

README.md
=> fixes #64, added travis and xo badge

app/main/index.js, app/package.json, package.json
=> fixes #67, added some event listeners to app

app/main/index.js
=> fixes #71, auto hide menubar as default

.gitignore, package-lock.json
=> fixes #73, remove package-lock.json from .gitignore

app/main/index.js, package.json
Fixes #80 
Here's the npm package of the published app - https://www.npmjs.com/package/susi_desktop
* Install : `sudo npm i -g susi_desktop`.
* Start : `susi`
=> fixes #80, published the app as npm module

app/package-lock.json, electron-builder.json, package.json
Fixes #37 and #42 
Use `npm run pack` to generate installer.
=> Added build script

README.md
=> fixed #87, added relevant npm badges

app/package.json, package-lock.json, package.json
The npm module needs to be re-published after the changes made recently but it can't be republished under the same package version hence updated this. I'll republish the module once this gets merged.
=> Updated app version

.gitignore
=> Fixes #92, add dist directory to .gitignore

package-lock.json, package.json
Updated the app version to republish the npm module, since some change have been done recently and we can't publish the module with the same app version.
=> Update app version to republish the npm module

.editorconfig
=> Improved .editorconfig

.github/CONTRIBUTING.md
Fixes #100 
@BrainBuzzer @aashutoshrathi Please review. Thanks!!
=> Fixes #100 Add CONTRIBUTING.md 

package.json
Updated the package to latest build here - https://www.npmjs.com/package/susi_desktop
=> Update package version for updating npm module.

Dockerfile, README.md
Fixes #103 
Added `Dockerfile` and its auto deployment button.
@BrainBuzzer Please review. Thanks !!
=> Fixes #103 Dockerize susi_desktop

.github/ISSUE_TEMPLATE.md
=> Comment out suggestions in Issue Template

.eslintrc.js
=> Fixed the conflict between travis and codacy

package.json
=> Fixed #118: Add precommit hooks to check code quality before commit
